name: kline_chart
description: flutter kline chart plugin
version: 0.0.1+1

homepage: https://github.com/AscenX/kline_chart
repository: https://github.com/AscenX/kline_chart


environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.24.0
